# frozen_string_literal: true

# ETags that include the import map digest, and the development cache sweeper.
class Views::Docs::Pages::Caching < DocsUI::Page
  title "Caching & ETags"
  eyebrow "Serving"

  def lead = "Fold the import map into your ETags, and keep the map fresh while you edit JavaScript in development."

  def content
    etags
    sweeping
    legacy_browsers
  end

  private

  def etags
    DocsUI::Section("A digest of the import map in your ETag") do
      md <<~'MD'
        If you use ETags generated by Rails helpers like `stale?` or `fresh_when`,
        the digest of the import map has to be part of the calculation. Otherwise
        the application keeps answering `304 Not Modified` after your JavaScript
        changed. `stale_when_importmap_changes` adds the digest to the ETag for
        HTML requests:
      MD
      DocsUI::Code(<<~RUBY, filename: "app/controllers/application_controller.rb")
        class ApplicationController < ActionController::Base
          stale_when_importmap_changes
        end
      RUBY
      md <<~'MD'
        Under the hood that is `Rails.application.importmap.digest(resolver: helpers)`,
        a SHA1 of the rendered import map JSON, which you can use directly in an
        `etag { … }` block if you'd rather scope it yourself.
      MD
    end
  end

  def sweeping
    DocsUI::Section("Sweeping the cache in development and test") do
      md <<~'MD'
        The import map is cached once rendered. In development and test a file
        watcher on `app/javascript` and `vendor/javascript` clears that cache before
        each request when a file changed, so a new controller shows up in the map
        without a restart. That is `config.importmap.sweep_cache`, on by default in
        those environments.

        An engine, or an app with JavaScript elsewhere, adds its directories to the
        watch list:
      MD
      DocsUI::Code(<<~RUBY, filename: "my_engine/lib/my_engine/engine.rb")
        initializer "my-engine.importmap" do |app|
          app.config.importmap.cache_sweepers << Engine.root.join("app/assets/javascripts")
        end
      RUBY
      md <<~'MD'
        `config/importmap.rb` itself is reloaded by a separate reloader whenever any
        file in `config.importmap.paths` changes; removing a pin still needs a
        restart for it to disappear from the rendered map and the preloads.
      MD
    end
  end

  def legacy_browsers
    DocsUI::Section("Legacy browsers such as Safari on iOS 15") do
      md <<~'MD'
        For a browser without native import map support, load
        [es-module-shims](https://github.com/guybedford/es-module-shims) before the
        import map tags:
      MD
      DocsUI::Code(<<~ERB, filename: "app/views/layouts/application.html.erb")
        <script async src="https://ga.jspm.io/npm:es-module-shims@1.8.2/dist/es-module-shims.js" data-turbo-track="reload"></script>
        <%= javascript_importmap_tags %>
      ERB
    end
  end
end
